version: '3'

services:
  dns:
    build: ./dns
    command: named -c /etc/bind/named.conf -g -u named
    container_name: dns
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: always
    volumes:
      - ./dns/etc/bind/named.conf:/etc/bind/named.conf
      - ./dns/etc/bind/zone/:/etc/bind/zone
  
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - ./elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      # fluentd configurations
      - ./fluentd/fluentd/etc:/fluentd/etc
      # nginx logs
      - ./nginx/var/log/nginx:/var/log/nginx
    ports:
      - 24224:24224/tcp
      - 24224:24224/udp
    depends_on:
      - elasticsearch
  
  kibana:
    build: ./kibana
    container_name: kibana
    ports:
      - 5601:5601
  
  nginx:
    build:
      context: ./nginx
    command: sh /src/init.sh
    container_name: nginx
    ports:
      - 8000:80/tcp
      - 443:443
    tty: true
    volumes:
      # ssl configurations
      - ./nginx/etc/certs:/etc/certs
      # nginx configurations
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
      # flask source code
      - ./nginx/src/:/src/
      - ./nginx/usr/share/nginx/html/:/usr/share/nginx/html/
      # nginx logs
      - ./nginx/var/log/nginx:/var/log/nginx