version: '3'

services:
  dns:
    build:
      context: ./dns/
    command: named -c /etc/bind/named.conf -g -u named
    container_name: dns
    ports:
      - 53:53
      - 53:53/udp
    restart: always
    volumes:
      - ./dns/etc/bind/named.conf:/etc/bind/named.conf
      - ./dns/etc/bind/zone/:/etc/bind/zone
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        hard: -1
        soft: -1
    # volumes:
    #   - ./elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/fluentd/etc:/fluentd/etc
      - ./nginx/var/log/nginx:/var/log/nginx
    ports:
      - 24224:24224
    # depends_on:
    #   - elasticsearch
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    # platform: linux/amd64
    ports:
      - 5601:5601
  
  nginx:
    build:
      context: ./nginx
    command: sh /src/init.sh
    container_name: nginx
    ports:
      - 80:80
    tty: true
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/src/:/src/
      - ./nginx/usr/share/nginx/html/:/usr/share/nginx/html/
      - ./nginx/var/log/nginx:/var/log/nginx